name: CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  CD:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Configure SSH Google Cloud
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/google-cloud.key
          chmod 600 ~/.ssh/google-cloud.key
          echo "$GOOGLE_CLOUD_SSH_PASSWORD" | sshpass -p "$GOOGLE_CLOUD_SSH_PASSWORD" ssh-add -
          cat >>~/.ssh/config <<END
          Host google-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/google-cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.GOOGLE_CLOUD_SSH_USER }}
          SSH_KEY: ${{ secrets.GOOGLE_CLOUD_SSH_KEY }}
          SSH_HOST: ${{ secrets.GOOGLE_CLOUD_SSH_HOST }}
          GOOGLE_CLOUD_SSH_PASSWORD: ${{ secrets.GOOGLE_CLOUD_SSH_PASSWORD }}
        
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Install dependencies
        run: npm install
      
      - name: Run the tests
        run: npm run test -- --coverage
        env:
          CI: true
          
      - name: Deploy the aplicattion
        run: |
          sshpass -p $GOOGLE_CLOUD_SSH_PASSWORD ssh google-cloud 'sudo systemctl stop react-app'
          sshpass -p $GOOGLE_CLOUD_SSH_PASSWORD ssh google-cloud 'sudo rm -rf /app/react-app'
          scp -r build google-cloud:/home/github/react-app
          sshpass -p $GOOGLE_CLOUD_SSH_PASSWORD ssh google-cloud 'sudo mv /home/github/react-app /app/react-app'
          sshpass -p $GOOGLE_CLOUD_SSH_PASSWORD ssh google cloud 'sudo systemctl start react-app'

